name: Lint, Test, and Setup Services

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 24

    - name: Install dependencies
      run: npm install

    - name: Install Redis CLI
      run: |
        echo "set man-db/auto-update false" | debconf-communicate
        dpkg-reconfigure man-db
        sudo apt-get update
        sudo apt-get install -y redis-tools

    - name: Wait for services to be ready
      run: |
        until pg_isready -h localhost -p 5432; do
          echo "Waiting for Postgres...";
          sleep 2;
        done
        until redis-cli ping; do
          echo "Waiting for Redis...";
          sleep 2;
        done

    - name: Run lint
      run: npm run lint

    - name: Run tests
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/testdb
        REDIS_URL: redis://localhost:6379
        SESSION_SECRET: Matt is Jobber's biggest fan and he will die on that hill
      run: npm test